### ISSUE TITLE
cant allocate enogh memory

### ISSUE THREAD

**Issue by kubinka0505** [haoheliu/versatile_audio_super_resolution#27]
Logs:
```Loading AudioSR: basic Loading model on cuda:0 /usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.) return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined] /usr/local/lib/python3.10/dist-packages/torchaudio/transforms/_transforms.py:611: UserWarning: Argument 'onesided' has been deprecated and has no influence on the behavior of this module. warnings.warn( DiffusionWrapper has 258.20 M params. Warning: audio is longer than 10.24 seconds, may degrade the model performance. It's recommand to truncate your audio to 5.12 seconds before input to AudioSR to get the best performance. Traceback (most recent call last): File "/usr/local/bin/audiosr", line 115, in <module> waveform = super_resolution( File "/usr/local/lib/python3.10/dist-packages/audiosr/pipeline.py", line 168, in super_resolution waveform = latent_diffusion.generate_batch( File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/audiosr/latent_diffusion/models/ddpm.py", line 1493, in generate_batch z, c = self.get_input( File "/usr/local/lib/python3.10/dist-packages/audiosr/latent_diffusion/models/ddpm.py", line 837, in get_input encoder_posterior = self.encode_first_stage(x) File "/usr/local/lib/python3.10/dist-packages/audiosr/latent_diffusion/models/ddpm.py", line 935, in encode_first_stage return self.first_stage_model.encode(x) File "/usr/local/lib/python3.10/dist-packages/audiosr/latent_encoder/autoencoder.py", line 106, in encode h = self.encoder(x) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/audiosr/latent_diffusion/modules/diffusionmodules/model.py", line 526, in forward h = self.down[i_level].block[i_block](hs[-1], temb) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/audiosr/latent_diffusion/modules/diffusionmodules/model.py", line 157, in forward h = self.norm1(h) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/normalization.py", line 273, in forward return F.group_norm( File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 2530, in group_norm return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled) torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.19 GiB (GPU 0; 14.75 GiB total capacity; 10.02 GiB already allocated; 3.29 GiB free; 10.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF 
```

**Comment by vb87** [comment]
works for me when I do it with this launcher code, but you need to have at least 6GB vram GPU:
```
import subprocess
import torch
import time
import gc
from pynvml import nvmlInit, nvmlDeviceGetHandleByIndex, nvmlDeviceGetMemoryInfo
def clear_gpu_memory():
    torch.cuda.empty_cache()
    gc.collect()
def wait_until_enough_gpu_memory(min_memory_available, max_retries=10, sleep_time=5):
    nvmlInit()
    handle = nvmlDeviceGetHandleByIndex(torch.cuda.current_device())
    for _ in range(max_retries):
        info = nvmlDeviceGetMemoryInfo(handle)
        if info.free >= min_memory_available:
            break
        print(f"Waiting for {min_memory_available} bytes of free GPU memory. Retrying in {sleep_time} seconds...")
        time.sleep(sleep_time)
    else:
        raise RuntimeError(f"Failed to acquire {min_memory_available} bytes of free GPU memory after {max_retries} retries.")
min_memory_available = 5 * 1024 * 1024 * 1024  # 5GB
clear_gpu_memory()
wait_until_enough_gpu_memory(min_memory_available)
input_audio_file = "output.mp3"
subprocess.run(["cmd.exe", "/c" , "audiosr", "-i", input_audio_file, "-s", ".", "-d", "cuda"])

```
